<?php
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tutorial</title>
    <link rel="stylesheet" href="tutorial.css">
</head>
<body>

    <header>
            <div class="container">
                <div class="logo">
                    <a href="index.php">Tutorial</a>
                </div>
                <nav>
                    <ul>
                        <li class="<?php echo ($current_page == 'hp') ? 'active' : ''; ?>">
                            <a href="hp.php">JadiSigma</a>
                        <li class="<?php echo ($current_page == 'Tampilan') ? 'active' : ''; ?>">
                            <a href="look.php">Tampilan</a>
                        <li class="<?php echo ($current_page == 'home') ? 'active' : ''; ?>">
                            <a href="index.php">Home</a>
                        </li>
                        <li class="<?php echo ($current_page == 'about') ? 'active' : ''; ?>">
                            <a href="about.php">About Us</a>
                        </li>
                        <li class="<?php echo ($current_page == 'work') ? 'active' : ''; ?>">
                            <a href="hobby.php">Komunitas</a>
                        </li>
                        <li class="<?php echo ($current_page == 'info') ? 'active' : ''; ?>">
                            <a href="media.php">Sosial Media</a>
                        </li>
                        <li class="<?php echo ($current_page == 'tutorial') ? 'active' : ''; ?>">
                            <a href="tutorial.php">Tutorial</a>
                        </li>
                        <li class="<?php echo ($current_page == 'login') ? 'active' : ''; ?>">
                            <a href="masuk/login.php">Login</a>
                        </li>
                        <li class="<?php echo ($current_page == 'register') ? 'active' : ''; ?>">
                            <a href="masuk/register.php">Register</a>
                        </li>   
                    </ul>
                </nav>
            </div>
        </header>
    
        </head>
<body>
    <div class="container">
        <header>
            <h1>🏋️ Tutorial Alat Gym</h1>
            <p class="subtitle">Panduan Lengkap Penggunaan Peralatan Fitness</p>
        </header>

        <div class="search-container">
            <input type="text" class="search-box" id="searchBox" placeholder="Cari alat gym...">
        </div>

        <div class="filter-buttons">
            <button class="filter-btn active" data-filter="all">Semua</button>
            <button class="filter-btn" data-filter="beginner">Pemula</button>
            <button class="filter-btn" data-filter="intermediate">Menengah</button>
            <button class="filter-btn" data-filter="advanced">Lanjutan</button>
        </div>

        <div class="equipment-grid" id="equipmentGrid">
            <!-- Equipment cards will be generated by PHP -->
        </div>
    </div>

    <!-- Modal -->
    <div id="equipmentModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <div id="modalContent"></div>
        </div>
    </div>

    <?php
    // Data alat gym
    $gymEquipment = [
        [
            'name' => 'Treadmill',
            'category' => 'Cardio',
            'difficulty' => 'beginner',
            'muscles' => ['Kaki', 'Kardiovaskular'],
            'steps' => [
                'Naik ke treadmill dengan hati-hati',
                'Mulai dengan kecepatan rendah (2-3 km/jam)',
                'Pegang handrail jika diperlukan untuk keseimbangan',
                'Tingkatkan kecepatan secara bertahap',
                'Jaga postur tubuh tetap tegak',
                'Turunkan kecepatan secara perlahan sebelum berhenti'
            ],
            'tips' => 'Mulai dengan 10-15 menit untuk pemula. Gunakan sepatu olahraga yang nyaman.',
            'warning' => 'Jangan melompat turun saat treadmill masih bergerak. Selalu gunakan safety clip.'
        ],
        [
            'name' => 'Bench Press',
            'category' => 'Strength',
            'difficulty' => 'intermediate',
            'muscles' => ['Dada', 'Bahu', 'Triceps'],
            'steps' => [
                'Berbaring di bangku dengan punggung rata',
                'Posisikan mata tepat di bawah barbell',
                'Pegang barbell dengan grip selebar bahu',
                'Angkat barbell dari rack dengan bantuan spotter',
                'Turunkan barbell ke dada dengan kontrol',
                'Dorong barbell kembali ke posisi awal',
                'Kembalikan ke rack dengan bantuan spotter'
            ],
            'tips' => 'Selalu gunakan spotter untuk keamanan. Mulai dengan beban ringan.',
            'warning' => 'Jangan pernah melakukan bench press tanpa spotter atau safety bar.'
        ],
        [
            'name' => 'Squat Rack',
            'category' => 'Strength',
            'difficulty' => 'intermediate',
            'muscles' => ['Quadriceps', 'Glutes', 'Hamstring'],
            'steps' => [
                'Posisikan barbell di atas bahu (trap muscles)',
                'Berdiri dengan kaki selebar bahu',
                'Turunkan tubuh dengan mendorong pinggul ke belakang',
                'Jaga lutut sejajar dengan jari kaki',
                'Turun hingga paha sejajar dengan lantai',
                'Dorong melalui tumit untuk kembali berdiri'
            ],
            'tips' => 'Jaga punggung tetap lurus. Fokus pada teknik sebelum menambah beban.',
            'warning' => 'Pastikan safety bar terpasang. Jangan membiarkan lutut masuk ke dalam.'
        ],
        [
            'name' => 'Dumbbells',
            'category' => 'Strength',
            'difficulty' => 'beginner',
            'muscles' => ['Seluruh Tubuh'],
            'steps' => [
                'Pilih berat yang sesuai dengan kemampuan',
                'Pegang dumbbell dengan grip yang kuat',
                'Jaga postur tubuh tetap baik',
                'Lakukan gerakan dengan kontrol penuh',
                'Fokus pada otot yang sedang dilatih',
                'Kembalikan dumbbell ke tempatnya setelah selesai'
            ],
            'tips' => 'Mulai dengan beban ringan untuk mempelajari teknik. Variasikan latihan.',
            'warning' => 'Jangan mengayunkan beban. Kontrol gerakan di kedua arah.'
        ],
        [
            'name' => 'Leg Press Machine',
            'category' => 'Strength',
            'difficulty' => 'beginner',
            'muscles' => ['Quadriceps', 'Glutes', 'Hamstring'],
            'steps' => [
                'Duduk di mesin dengan punggung rata',
                'Posisikan kaki di platform selebar bahu',
                'Lepaskan pengaman dengan hati-hati',
                'Turunkan beban dengan kontrol',
                'Dorong platform kembali ke posisi awal',
                'Pasang kembali pengaman sebelum turun'
            ],
            'tips' => 'Jangan mengunci lutut sepenuhnya. Bernapas dengan teratur.',
            'warning' => 'Selalu gunakan pengaman. Jangan turunkan beban terlalu dalam.'
        ],
        [
            'name' => 'Pull-up Bar',
            'category' => 'Strength',
            'difficulty' => 'advanced',
            'muscles' => ['Latissimus Dorsi', 'Biceps', 'Bahu'],
            'steps' => [
                'Pegang bar dengan grip overhand',
                'Gantung dengan lengan penuh terulur',
                'Tarik tubuh ke atas hingga dagu melewati bar',
                'Tahan sejenak di posisi atas',
                'Turunkan tubuh dengan kontrol',
                'Ulangi gerakan tanpa ayunan'
            ],
            'tips' => 'Gunakan assisted pull-up machine untuk pemula. Fokus pada teknik.',
            'warning' => 'Jangan mengayun atau menggunakan momentum berlebihan.'
        ],
        [
            'name' => 'Elliptical Machine',
            'category' => 'Cardio',
            'difficulty' => 'beginner',
            'muscles' => ['Seluruh Tubuh', 'Kardiovaskular'],
            'steps' => [
                'Naik ke mesin dengan memegang handrail',
                'Posisikan kaki di pedal dengan aman',
                'Mulai dengan gerakan perlahan',
                'Koordinasikan gerakan tangan dan kaki',
                'Jaga postur tubuh tetap tegak',
                'Turunkan intensitas sebelum berhenti'
            ],
            'tips' => 'Variasikan arah gerakan (maju/mundur). Gunakan program yang tersedia.',
            'warning' => 'Jangan berhenti mendadak. Turunkan kecepatan secara bertahap.'
        ],
        [
            'name' => 'Cable Machine',
            'category' => 'Strength',
            'difficulty' => 'intermediate',
            'muscles' => ['Seluruh Tubuh'],
            'steps' => [
                'Pilih attachment yang sesuai',
                'Atur beban yang tepat',
                'Posisikan tubuh dengan stabil',
                'Tarik atau dorong dengan kontrol',
                'Fokus pada otot target',
                'Kembalikan beban dengan perlahan'
            ],
            'tips' => 'Cable machine sangat fleksibel untuk berbagai latihan. Eksplorasi berbagai sudut.',
            'warning' => 'Pastikan attachment terpasang dengan kuat. Jaga posisi tubuh stabil.'
        ]
    ];

    // Generate equipment cards
    echo "<script>";
    echo "const equipmentData = " . json_encode($gymEquipment) . ";";
    echo "</script>";
    ?>

    <script>
        // Generate equipment cards
        function generateCards(data) {
            const grid = document.getElementById('equipmentGrid');
            grid.innerHTML = '';
            
            data.forEach((equipment, index) => {
                const card = document.createElement('div');
                card.className = 'equipment-card';
                card.dataset.difficulty = equipment.difficulty;
                card.onclick = () => openModal(equipment);
                
                const difficultyText = {
                    'beginner': 'Pemula',
                    'intermediate': 'Menengah',
                    'advanced': 'Lanjutan'
                };
                
                card.innerHTML = `
                    <div class="card-header">
                        <h3>${equipment.name}</h3>
                        <div class="difficulty">${difficultyText[equipment.difficulty]}</div>
                    </div>
                    <div class="card-body">
                        <div class="muscle-groups">
                            ${equipment.muscles.map(muscle => `<span class="muscle-tag">${muscle}</span>`).join('')}
                        </div>
                        <p><strong>Kategori:</strong> ${equipment.category}</p>
                        <p><strong>Jumlah Langkah:</strong> ${equipment.steps.length}</p>
                    </div>
                `;
                
                grid.appendChild(card);
            });
        }

        // Open modal with equipment details
        function openModal(equipment) {
            const modal = document.getElementById('equipmentModal');
            const modalContent = document.getElementById('modalContent');
            
            const difficultyText = {
                'beginner': 'Pemula',
                'intermediate': 'Menengah',
                'advanced': 'Lanjutan'
            };
            
            modalContent.innerHTML = `
                <h2>${equipment.name}</h2>
                <p><strong>Tingkat Kesulitan:</strong> <span class="difficulty">${difficultyText[equipment.difficulty]}</span></p>
                <div class="muscle-groups">
                    <strong>Target Otot:</strong><br>
                    ${equipment.muscles.map(muscle => `<span class="muscle-tag">${muscle}</span>`).join('')}
                </div>
                
                <div class="steps">
                    <h3>Langkah-langkah Penggunaan:</h3>
                    ${equipment.steps.map((step, index) => `
                        <div class="step">
                            <span class="step-number">${index + 1}</span>
                            ${step}
                        </div>
                    `).join('')}
                </div>
                
                <div class="tips">
                    <div class="tips-title">💡 Tips:</div>
                    ${equipment.tips}
                </div>
                
                <div class="warning">
                    <div class="warning-title">⚠️ Peringatan:</div>
                    ${equipment.warning}
                </div>
            `;
            
            modal.style.display = 'block';
        }

        // Search functionality
        document.getElementById('searchBox').addEventListener('input', function(e) {
            const searchTerm = e.target.value.toLowerCase();
            const filteredData = equipmentData.filter(equipment => 
                equipment.name.toLowerCase().includes(searchTerm) ||
                equipment.category.toLowerCase().includes(searchTerm) ||
                equipment.muscles.some(muscle => muscle.toLowerCase().includes(searchTerm))
            );
            generateCards(filteredData);
        });

        // Filter functionality
        document.querySelectorAll('.filter-btn').forEach(btn => {
            btn.addEventListener('click', function() {
                // Remove active class from all buttons
                document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
                // Add active class to clicked button
                this.classList.add('active');
                
                const filter = this.dataset.filter;
                let filteredData = equipmentData;
                
                if (filter !== 'all') {
                    filteredData = equipmentData.filter(equipment => equipment.difficulty === filter);
                }
                
                generateCards(filteredData);
            });
        });

        // Modal functionality
        document.querySelector('.close').addEventListener('click', function() {
            document.getElementById('equipmentModal').style.display = 'none';
        });

        window.addEventListener('click', function(e) {
            const modal = document.getElementById('equipmentModal');
            if (e.target === modal) {
                modal.style.display = 'none';
            }
        });

        // Initialize page
        document.addEventListener('DOMContentLoaded', function() {
            generateCards(equipmentData);
        });
    </script>
    
    <footer>
        <div class="container">
            <p>&copy; <?php echo date('Y'); ?> Kelompok Kita</p>
        </div>
    </footer>
</body>
</html>